#!/bin/bash
# Recursively search subdirectories for 'README.md' and prepend them
# into the REAMDME.md in the current directory.
for f in $(find -mindepth 2 -name README.md); do
    if grep "$f" README.md > /dev/null; then
   	continue
    fi
    d=$(dirname $f)
    echo "<!---  $f --->" > /tmp/README.md
    echo "# $(basename $d)" | sed "s/_/ experiment: /2" | sed "s/_/ /g" >> /tmp/README.md
    sed -e "s,\!\[\](,\!\[\](${d:2}\/," $f >> /tmp/README.md
    echo "" >> /tmp/README.md
    cat README.md >> /tmp/README.md
    mv /tmp/README.md README.md
done
